[pytest]
# Where to discover tests
testpaths = src

# Match test modules and files
python_files = test_*.py tests.py
python_classes = Test*
python_functions = test_*

# Run with verbose output; use -v -v for extra verbosity
addopts = -v